language: python

python:
  - "2.7"

install:
  - make travis_install

script: pytest

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: refactor
