#!/usr/bin/env python

import yaml
import json
import shutil
import fileinput
import time
import re

JSON_FOLDER = "dist/json"
YAML_FILE = "src/quotes.yaml"
HTML_FILE = "dist/index.html"

print("Loading...")

with open(YAML_FILE) as f:
    data = yaml.safe_load(f)

print("Generating JSON...")

for i, q in enumerate(data):
    filename = "%s/%s.json" % (JSON_FOLDER, str(i).zfill(5))

    if 'text' in q:
        q['text'] = q['text'].rstrip()
    if 'ctx' in q:
        q['ctx'] = q['ctx'].rstrip()

    with open(filename, 'w') as f:
        f.write(json.dumps(q, ensure_ascii=False))

print("Fix index.html...")

for linenum, line in enumerate(fileinput.FileInput(HTML_FILE, inplace=1)):
    pattern_app = re.compile(r"(app\.js\?ts=)\d+")
    pattern_style = re.compile(r"(style\.css\?ts=)\d+")
    pattern_length = re.compile(r"(var\sLENGTH\s=\s)\d+")
    replace = r"\g<1>%d" % int(time.time())
    replace_length = r"\g<1>%d" % len(data)
    if "app.js?ts=" in line:
        print(re.sub(pattern_app, replace, line).rstrip())
    elif "style.css?ts=" in line:
        print(re.sub(pattern_style, replace, line).rstrip())
    elif "var LENGTH =" in line:
        print(re.sub(pattern_length, replace_length, line).rstrip())
    else:
        print(line.rstrip())


print("-------------------")
print("TOTAL QUOTES: %d" % len(data))
print("Done.")
